---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress-deployer
  namespace: wordpress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wordpress-deployer
  namespace: wordpress
rules:
  # Deployments - for WordPress and MySQL
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # ReplicaSets - managed by Deployments
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]

  # Services - to expose WordPress and MySQL
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # PersistentVolumeClaims - for data storage
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # ConfigMaps - for configuration
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Secrets - for passwords and sensitive data
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Pods - for monitoring and debugging
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  # Pod logs - for debugging
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]

  # ServiceAccounts - for Helm chart deployment
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Ingresses - for exposing WordPress
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # SecretImports - for importing MySQL password from secrets namespace
  - apiGroups: ["secretgen.carvel.dev"]
    resources: ["secretimports"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-deployer-binding
  namespace: wordpress
subjects:
  - kind: ServiceAccount
    name: wordpress-deployer
    namespace: wordpress
roleRef:
  kind: Role
  name: wordpress-deployer
  apiGroup: rbac.authorization.k8s.io