---
# Custom ClusterRole for Carol - Edit existing resources only (no create)
# Note: This is a ClusterRole but will be bound at namespace level via RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edit-existing-only
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]

---
# RoleBinding for Alice (admin - full access to wordpress namespace)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-admins-binding
  namespace: wordpress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: wordpress-admins

---
# RoleBinding for Carol (edit existing only - no create permission)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-editors-binding
  namespace: wordpress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit-existing-only
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: wordpress-editors

---
# Custom ClusterRole for Bob - View with port-forward capability
# Note: This is a ClusterRole but will be bound at namespace level via RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-with-portforward
rules:
# Include all standard view permissions
- apiGroups: [""]
  resources: ["configmaps", "endpoints", "persistentvolumeclaims", "persistentvolumeclaims/status",
              "pods", "replicationcontrollers", "replicationcontrollers/scale", "serviceaccounts",
              "services", "services/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["bindings", "events", "limitranges", "namespaces/status", "pods/log", "pods/status",
              "replicationcontrollers/status", "resourcequotas", "resourcequotas/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["controllerrevisions", "daemonsets", "daemonsets/status", "deployments",
              "deployments/scale", "deployments/status", "replicasets", "replicasets/scale",
              "replicasets/status", "statefulsets", "statefulsets/scale", "statefulsets/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers", "horizontalpodautoscalers/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "cronjobs/status", "jobs", "jobs/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["daemonsets", "daemonsets/status", "deployments", "deployments/scale",
              "deployments/status", "ingresses", "ingresses/status", "networkpolicies",
              "replicasets", "replicasets/scale", "replicasets/status", "replicationcontrollers/scale"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets", "poddisruptionbudgets/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingresses/status", "networkpolicies"]
  verbs: ["get", "list", "watch"]
# Add port-forward capability
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]

---
# RoleBinding for Bob (view with port-forward - read-only access + port-forward to wordpress namespace)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-viewers-binding
  namespace: wordpress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-with-portforward
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: wordpress-viewers
